/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cis.frames;

import java.awt.Color;
import java.text.DateFormat;
import java.util.Date;

/**
 *
 * @author kevin
 */
public class JHeader extends javax.swing.JFrame {

    String usuario = "Kevin Vallio";
    String perfil = "Perfil 1";
    Boolean camera = false;
    Boolean leitor = false;

    /**
     * Creates new form JHeader
     */
    public JHeader() {
        initComponents();
        setText();
    }

    public boolean initComp(){
         return true;
    }
    
    public String getHeaderData() {

        Date data = new Date();
        DateFormat dff = DateFormat.getDateInstance(DateFormat.FULL);
        String formatedData = dff.format(data);
        formatedData = formatedData.substring(0, 1).toUpperCase() + formatedData.substring(1).toLowerCase();
        System.out.println(formatedData);
        return formatedData;
    }

    public void setText() {
        jDataText.setText(getHeaderData());
        jUserName.setText("Olá, " + usuario);
        jPerfil.setText("Perfil: " + perfil);

        if (camera) {
            jCamera.setText("Câmera conectada");
            jCamera.setForeground(Color.black);
        } else {
            jCamera.setText("Câmera desconectada");
            jCamera.setForeground(Color.red);
        }

        if (leitor) {
            jLeitor.setText("Leitor biométrico conectado");
            jLeitor.setForeground(Color.black);
        } else {
            jLeitor.setText("Leitor biométrico desconectado");
            jLeitor.setForeground(Color.red);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDataText = new javax.swing.JLabel();
        jUserName = new javax.swing.JLabel();
        jPerfil = new javax.swing.JLabel();
        jCamera = new javax.swing.JLabel();
        jLeitor = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 140));
        setResizable(false);
        getContentPane().setLayout(null);

        jDataText.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jDataText.setForeground(new java.awt.Color(255, 255, 255));
        jDataText.setText("Data");
        getContentPane().add(jDataText);
        jDataText.setBounds(180, 20, 360, 30);

        jUserName.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jUserName.setForeground(new java.awt.Color(255, 255, 255));
        jUserName.setText("Name");
        getContentPane().add(jUserName);
        jUserName.setBounds(180, 50, 380, 40);

        jPerfil.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jPerfil.setForeground(new java.awt.Color(255, 255, 255));
        jPerfil.setText("Perfil");
        getContentPane().add(jPerfil);
        jPerfil.setBounds(180, 90, 390, 24);

        jCamera.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jCamera.setForeground(new java.awt.Color(255, 255, 255));
        jCamera.setText("Câmera");
        getContentPane().add(jCamera);
        jCamera.setBounds(860, 34, 360, 20);

        jLeitor.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLeitor.setForeground(new java.awt.Color(255, 255, 255));
        jLeitor.setText("Leitor");
        getContentPane().add(jLeitor);
        jLeitor.setBounds(860, 80, 360, 30);

        jButton1.setBackground(new java.awt.Color(90, 181, 177));
        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sair");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1250, 50, 90, 30);

        jBackground.setBackground(new java.awt.Color(240, 240, 40));
        jBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/header_complete.png"))); // NOI18N
        jBackground.setText("jLabel1");
        jBackground.setMaximumSize(new java.awt.Dimension(1366, 140));
        jBackground.setMinimumSize(new java.awt.Dimension(1366, 140));
        jBackground.setPreferredSize(new java.awt.Dimension(1366, 140));
        getContentPane().add(jBackground);
        jBackground.setBounds(0, 0, 1366, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        JFrameLogin login = new JFrameLogin();
        login.setSize(360,430);
        login.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JHeader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JHeader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JHeader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JHeader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JHeader().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBackground;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jCamera;
    private javax.swing.JLabel jDataText;
    private javax.swing.JLabel jLeitor;
    private javax.swing.JLabel jPerfil;
    private javax.swing.JLabel jUserName;
    // End of variables declaration//GEN-END:variables
}
